// resources/js/vue/components/fields/AdvancedField.vue
<!--
  Advanced field components wrapper.

  Renders file upload and date picker fields
  using @artisanpack-ui/vue components.

  @package    ArtisanPack_UI
  @subpackage Forms
  @since      1.1.0
-->
<script setup lang="ts">
import { computed } from 'vue';
import { DatePicker, FileUpload } from '@artisanpack-ui/vue/form';
import type { FormField, DisplayConfig } from '../../../types/artisanpack-forms';

const props = defineProps<{
	field: FormField;
	modelValue: unknown;
	error?: string;
	displayConfig: DisplayConfig;
}>();

const emit = defineEmits<{
	'update:modelValue': [value: unknown];
	'fileChange': [file: File | File[]];
}>();

const stringValue = computed( () => String( props.modelValue ?? '' ) );

const showLabel = computed( () => props.displayConfig.label_position !== 'hidden' );
const labelText = computed( () => props.field.label ?? undefined );
const ariaLabel = computed( () =>
	props.displayConfig.label_position === 'hidden'
		? ( props.field.label ?? props.field.name )
		: undefined,
);

const allowedTypes = computed( () =>
	props.field.validation_rules?.allowed_types?.join( ',' ) ?? undefined,
);

function handleFilesSelected( fileList: FileList | null ): void {
	if ( !fileList || fileList.length === 0 ) {
		emit( 'fileChange', [] as File[] );

		return;
	}

	if ( fileList.length === 1 ) {
		emit( 'fileChange', fileList[0] );
	} else {
		emit( 'fileChange', Array.from( fileList ) );
	}
}
</script>

<template>
	<!-- File -->
	<FileUpload
		v-if="field.type === 'file'"
		:label="showLabel ? labelText : undefined"
		:aria-label="ariaLabel"
		:name="field.name"
		:accept="allowedTypes"
		:hint="field.help_text ?? undefined"
		:error="error"
		:required="field.is_required"
		:class="field.css_classes ?? undefined"
		with-drag-drop
		@files-selected="handleFilesSelected"
	/>

	<!-- Date -->
	<DatePicker
		v-else-if="field.type === 'date'"
		:label="showLabel ? labelText : undefined"
		:aria-label="ariaLabel"
		:name="field.name"
		:model-value="stringValue"
		:hint="field.help_text ?? undefined"
		:error="error"
		:required="field.is_required"
		:class="field.css_classes ?? undefined"
		:min="field.validation_rules?.min_date ?? undefined"
		:max="field.validation_rules?.max_date ?? undefined"
		:inline="displayConfig.label_position === 'beside'"
		@update:model-value="emit( 'update:modelValue', $event )"
	/>
</template>

// resources/js/react/components/fields/AdvancedField.tsx
/**
 * Advanced field components.
 *
 * Renders file upload and date picker fields
 * using @artisanpack-ui/react components.
 *
 * @package    ArtisanPack_UI
 * @subpackage Forms
 *
 * @since      1.1.0
 */

import { DatePicker, File as FileInput } from '@artisanpack-ui/react/form';

import type { FieldComponentProps } from './types';

/**
 * Renders a file upload field.
 */
export function FileField( { field, error, onFileChange, displayConfig }: FieldComponentProps ) {
	const rules = field.validation_rules;
	const allowedTypes = rules?.allowed_types?.join( ',' ) ?? undefined;

	return (
		<FileInput
			label={displayConfig.label_position !== 'hidden' ? ( field.label ?? undefined ) : undefined}
			aria-label={displayConfig.label_position === 'hidden' ? ( field.label ?? undefined ) : undefined}
			name={field.name}
			accept={allowedTypes}
			hint={field.help_text ?? undefined}
			error={error}
			required={field.is_required}
			className={field.css_classes ?? undefined}
			withDragDrop
			onFilesSelected={( fileList ) => {
				if ( !onFileChange ) {
					return;
				}

				if ( !fileList || fileList.length === 0 ) {
					onFileChange( [] );

					return;
				}

				if ( fileList.length === 1 ) {
					onFileChange( fileList[0] );
				} else {
					onFileChange( Array.from( fileList ) );
				}
			}}
		/>
	);
}

/**
 * Renders a date picker field.
 */
export function DateField( { field, value, error, onChange, displayConfig }: FieldComponentProps ) {
	return (
		<DatePicker
			label={displayConfig.label_position !== 'hidden' ? ( field.label ?? undefined ) : undefined}
			aria-label={displayConfig.label_position === 'hidden' ? ( field.label ?? undefined ) : undefined}
			name={field.name}
			value={String( value ?? '' )}
			hint={field.help_text ?? undefined}
			error={error}
			required={field.is_required}
			className={field.css_classes ?? undefined}
			onChange={( e ) => onChange( e.target.value )}
			min={field.validation_rules?.min_date ?? undefined}
			max={field.validation_rules?.max_date ?? undefined}
			inline={displayConfig.label_position === 'beside'}
		/>
	);
}
