// resources/js/react/components/admin/FormsList.tsx
/**
 * FormsList admin component.
 *
 * Displays a paginated list of forms with search, filtering, sorting,
 * and actions for creating, editing, duplicating, toggling publish
 * status, and deleting forms.
 *
 * @package    ArtisanPack_UI
 * @subpackage Forms
 *
 * @since      1.1.0
 */

import React, { useCallback, useEffect, useMemo, useState } from 'react';

import { Alert, Badge, Button, Input, Loading, Pagination, Select } from '@artisanpack-ui/react';

import type {
	Form,
	FormStatusFilter,
	PaginatedResponse,
	SortDirection,
	StoreFormRequest,
} from '../../../types/artisanpack-forms';
import { useApi } from '../../hooks/useApi';
import type { UseApiOptions } from '../../hooks/useApi';

/**
 * Hook that returns a debounced version of the given value.
 *
 * @since 1.1.0
 *
 * @param value   The value to debounce.
 * @param delayMs Delay in milliseconds.
 *
 * @return The debounced value.
 */
function useDebouncedValue<T>( value: T, delayMs: number ): T {
	const [debounced, setDebounced] = useState( value );

	useEffect( () => {
		const timer = setTimeout( () => setDebounced( value ), delayMs );
		return () => clearTimeout( timer );
	}, [value, delayMs] );

	return debounced;
}

/**
 * Renders submission count with optional unread badge.
 *
 * @since 1.1.0
 *
 * @param props       Component props.
 * @param props.form  The form whose submission counts to display.
 *
 * @return The rendered submission count element.
 */
function SubmissionCount( { form }: { form: Form } ): React.ReactElement {
	return (
		<>
			{form.total_submissions_count ?? 0}
			{( form.unread_submissions_count ?? 0 ) > 0 && (
				<Badge
					color="info"
					size="sm"
					className="ml-1"
					value={`${form.unread_submissions_count} new`}
				/>
			)}
		</>
	);
}

/** Props for the FormsList component. */
export interface FormsListProps extends UseApiOptions {
	/** Callback when a form is selected for editing. */
	onEditForm?: ( form: Form ) => void;
	/** Callback when the user clicks to create a new form. */
	onCreateForm?: () => void;
	/** Callback when a form is selected for viewing submissions. */
	onViewSubmissions?: ( form: Form ) => void;
	/** Optional CSS class name. */
	className?: string;
}

type SortColumn = 'name' | 'created_at';

/**
 * Admin forms list component with search, filter, sort, and CRUD actions.
 *
 * @example
 * ```tsx
 * <FormsList
 *   baseUrl="/api/v1/forms"
 *   onEditForm={(form) => navigate(`/forms/${form.slug}/edit`)}
 *   onCreateForm={() => navigate('/forms/create')}
 *   onViewSubmissions={(form) => navigate(`/forms/${form.slug}/submissions`)}
 * />
 * ```
 */
export function FormsList( {
	baseUrl,
	csrfToken,
	authorization,
	credentials,
	onEditForm,
	onCreateForm,
	onViewSubmissions,
	className,
}: FormsListProps ): React.ReactElement {
	const { get, post, put, del } = useApi( { baseUrl, csrfToken, authorization, credentials } );

	const [forms, setForms] = useState<PaginatedResponse<Form> | null>( null );
	const [isLoading, setIsLoading] = useState( true );
	const [error, setError] = useState<string | null>( null );

	// Filters and sorting
	const [search, setSearch] = useState( '' );
	const debouncedSearch = useDebouncedValue( search, 300 );
	const [statusFilter, setStatusFilter] = useState<FormStatusFilter>( 'all' );
	const [sortBy, setSortBy] = useState<SortColumn>( 'created_at' );
	const [sortDirection, setSortDirection] = useState<SortDirection>( 'desc' );
	const [currentPage, setCurrentPage] = useState( 1 );

	// Action states
	const [deletingId, setDeletingId] = useState<number | null>( null );
	const [duplicatingId, setDuplicatingId] = useState<number | null>( null );
	const [togglingId, setTogglingId] = useState<number | null>( null );

	const fetchForms = useCallback( async () => {
		setIsLoading( true );
		setError( null );

		try {
			const params: Record<string, string> = {
				page: String( currentPage ),
				sort_by: sortBy,
				sort_direction: sortDirection,
			};

			if ( debouncedSearch ) {
				params.search = debouncedSearch;
			}

			if ( statusFilter !== 'all' ) {
				params.status = statusFilter;
			}

			const data = await get<PaginatedResponse<Form>>( '/', params );
			setForms( data );
		} catch ( err ) {
			const message = err instanceof Error ? err.message : 'Failed to load forms.';
			setError( message );
		} finally {
			setIsLoading( false );
		}
	}, [get, currentPage, debouncedSearch, sortBy, sortDirection, statusFilter] );

	useEffect( () => {
		fetchForms();
	}, [fetchForms] );

	const handleSort = useCallback( ( column: SortColumn ) => {
		setSortBy( ( prev ) => {
			if ( prev === column ) {
				setSortDirection( ( d ) => ( d === 'asc' ? 'desc' : 'asc' ) );

				return prev;
			}

			setSortDirection( 'asc' );

			return column;
		} );
	}, [] );

	const handleDelete = useCallback( async ( form: Form ) => {
		if ( !window.confirm( `Are you sure you want to delete "${form.name}"?` ) ) {
			return;
		}

		setDeletingId( form.id );

		try {
			await del( `/${form.slug}` );
			await fetchForms();
		} catch ( err ) {
			const message = err instanceof Error ? err.message : 'Failed to delete form.';
			setError( message );
		} finally {
			setDeletingId( null );
		}
	}, [del, fetchForms] );

	// TODO: Backend duplicate endpoint would copy fields/steps/notifications.
	// Currently only copies form-level settings. A full duplicate API endpoint
	// should be added to the package for complete form cloning.
	const handleDuplicate = useCallback( async ( form: Form ) => {
		setDuplicatingId( form.id );

		try {
			const duplicateData: StoreFormRequest = {
				name: `${form.name} (Copy)`,
				description: form.description,
				submit_button_text: form.submit_button_text,
				success_message: form.success_message,
				redirect_url: form.redirect_url,
				is_active: false,
				is_multi_step: form.is_multi_step,
				show_progress_bar: form.show_progress_bar,
				allow_step_navigation: form.allow_step_navigation,
			};

			await post<{ data: Form }>( '/', duplicateData );
			await fetchForms();
		} catch ( err ) {
			const message = err instanceof Error ? err.message : 'Failed to duplicate form.';
			setError( message );
		} finally {
			setDuplicatingId( null );
		}
	}, [post, fetchForms] );

	const handleTogglePublish = useCallback( async ( form: Form ) => {
		setTogglingId( form.id );

		try {
			await put( `/${form.slug}`, { is_active: !form.is_active } );
			await fetchForms();
		} catch ( err ) {
			const message = err instanceof Error ? err.message : 'Failed to update form status.';
			setError( message );
		} finally {
			setTogglingId( null );
		}
	}, [put, fetchForms] );

	const sortIndicator = useCallback( ( column: SortColumn ): string => {
		if ( sortBy !== column ) {
			return '';
		}

		return sortDirection === 'asc' ? ' \u2191' : ' \u2193';
	}, [sortBy, sortDirection] );

	const getAriaSortValue = useCallback( ( column: SortColumn ): 'ascending' | 'descending' | 'none' => {
		if ( sortBy !== column ) {
			return 'none';
		}

		return sortDirection === 'asc' ? 'ascending' : 'descending';
	}, [sortBy, sortDirection] );

	const formsList = useMemo( () => forms?.data ?? [], [forms] );

	return (
		<div className={`space-y-6 ${className ?? ''}`.trim()}>
			{/* Header */}
			<div className="flex items-center justify-between">
				<h1 className="text-2xl font-bold">Forms</h1>
				{onCreateForm && (
					<Button
						color="primary"
						onClick={onCreateForm}
					>
						Create Form
					</Button>
				)}
			</div>

			{/* Filters */}
			<div className="flex flex-wrap items-center gap-3">
				<Input
					type="search"
					className="w-full max-w-xs"
					placeholder="Search forms..."
					value={search}
					onChange={( e ) => {
						setSearch( e.target.value );
						setCurrentPage( 1 );
					}}
				/>

				<Select
					value={statusFilter}
					options={[
						{ id: 'all', name: 'All Status' },
						{ id: 'active', name: 'Active' },
						{ id: 'inactive', name: 'Inactive' },
					]}
					optionValue="id"
					optionLabel="name"
					onChange={( e ) => {
						setStatusFilter( e.target.value as FormStatusFilter );
						setCurrentPage( 1 );
					}}
				/>
			</div>

			{/* Error */}
			{error && (
				<Alert color="error" dismissible onDismiss={() => setError( null )}>
					{error}
				</Alert>
			)}

			{/* Loading */}
			{isLoading && (
				<div className="flex items-center justify-center gap-3 py-12" role="status">
					<Loading size="md" />
					<span>Loading forms...</span>
				</div>
			)}

			{/* Table */}
			{!isLoading && formsList.length > 0 && (
				<div className="overflow-x-auto">
					<table className="table table-zebra">
						<thead>
							<tr>
								<th aria-sort={getAriaSortValue( 'name' )}>
									<Button
										color="ghost"
										size="sm"
										onClick={() => handleSort( 'name' )}
									>
										Name{sortIndicator( 'name' )}
									</Button>
								</th>
								<th>Status</th>
								<th>Submissions</th>
								<th aria-sort={getAriaSortValue( 'created_at' )}>
									<Button
										color="ghost"
										size="sm"
										onClick={() => handleSort( 'created_at' )}
									>
										Created{sortIndicator( 'created_at' )}
									</Button>
								</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							{formsList.map( ( form ) => (
								<tr key={form.id}>
									<td>
										<div className="flex flex-col">
											<button
												type="button"
												className="link link-hover font-medium text-left"
												onClick={() => onEditForm?.( form )}
											>
												{form.name}
											</button>
											{form.description && (
												<span className="text-sm text-base-content/60">
													{form.description}
												</span>
											)}
										</div>
									</td>
									<td>
										<Badge
											color={form.is_active ? 'success' : 'warning'}
											value={form.is_active ? 'Active' : 'Inactive'}
										/>
									</td>
									<td>
										{onViewSubmissions ? (
											<Button
												color="ghost"
												size="sm"
												onClick={() => onViewSubmissions( form )}
											>
												<SubmissionCount form={form} />
											</Button>
										) : (
											<span>
												<SubmissionCount form={form} />
											</span>
										)}
									</td>
									<td>
										{new Intl.DateTimeFormat( 'en-US', { year: 'numeric', month: 'short', day: 'numeric' } ).format( new Date( form.created_at ) )}
									</td>
									{( () => {
										const isRowProcessing = duplicatingId === form.id || togglingId === form.id || deletingId === form.id;

										return (
											<td>
												<div className="flex items-center gap-1">
													<Button
														color="ghost"
														size="sm"
														onClick={() => onEditForm?.( form )}
														title="Edit"
														disabled={isRowProcessing}
													>
														Edit
													</Button>
													<Button
														color="ghost"
														size="sm"
														onClick={() => handleDuplicate( form )}
														disabled={isRowProcessing}
														title="Duplicate"
													>
														{duplicatingId === form.id ? 'Duplicating...' : 'Duplicate'}
													</Button>
													<Button
														color="outline"
														size="sm"
														onClick={() => handleTogglePublish( form )}
														disabled={isRowProcessing}
														title={form.is_active ? 'Unpublish' : 'Publish'}
													>
														{togglingId === form.id
															? 'Updating...'
															: form.is_active
																? 'Unpublish'
																: 'Publish'}
													</Button>
													<Button
														color="error"
														size="sm"
														onClick={() => handleDelete( form )}
														disabled={isRowProcessing}
														title="Delete"
													>
														{deletingId === form.id ? 'Deleting...' : 'Delete'}
													</Button>
												</div>
											</td>
										);
									} )()}
								</tr>
							) )}
						</tbody>
					</table>
				</div>
			)}

			{/* Empty state */}
			{!isLoading && formsList.length === 0 && !error && (
				<div className="flex flex-col items-center justify-center gap-4 py-16 text-base-content/60">
					<p className="text-lg">No forms found.</p>
					{onCreateForm && (
						<Button
							color="primary"
							onClick={onCreateForm}
						>
							Create your first form
						</Button>
					)}
				</div>
			)}

			{/* Pagination */}
			{forms && forms.meta.last_page > 1 && (
				<Pagination
					currentPage={forms.meta.current_page}
					totalPages={forms.meta.last_page}
					onChange={setCurrentPage}
				/>
			)}
		</div>
	);
}

// resources/js/vue/components/admin/FormsList.vue
<!--
  FormsList admin component.

  Displays a paginated list of forms with search, filtering, sorting,
  and actions for creating, editing, duplicating, toggling publish
  status, and deleting forms.

  @package    ArtisanPack_UI
  @subpackage Forms
  @since      1.1.0
-->
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue';

import { Alert, Badge, Button, Input, Loading, Pagination, Select } from '@artisanpack-ui/vue';

import type {
	Form,
	FormStatusFilter,
	PaginatedResponse,
	SortDirection,
	StoreFormRequest,
} from '../../../types/artisanpack-forms';
import { useApi } from '../../composables/useApi';
import type { UseApiOptions } from '../../composables/useApi';

type SortColumn = 'name' | 'created_at';

const props = withDefaults( defineProps<UseApiOptions & {
	/** Optional CSS class name. */
	className?: string;
	/** Whether to show clickable submission counts (requires view-submissions listener). */
	showSubmissions?: boolean;
}>(), {
	csrfToken: undefined,
	authorization: undefined,
	credentials: undefined,
	className: undefined,
	showSubmissions: false,
} );

const emit = defineEmits<{
	'edit-form': [form: Form];
	'create-form': [];
	'view-submissions': [form: Form];
}>();

const { get, post, put, del } = useApi( {
	baseUrl: props.baseUrl,
	csrfToken: props.csrfToken,
	authorization: props.authorization,
	credentials: props.credentials,
} );

// Data state
const forms = ref<PaginatedResponse<Form> | null>( null );
const isLoading = ref( true );
const error = ref<string | null>( null );

// Filters and sorting
const search = ref( '' );
const debouncedSearch = ref( '' );
const statusFilter = ref<FormStatusFilter>( 'all' );
const sortBy = ref<SortColumn>( 'created_at' );
const sortDirection = ref<SortDirection>( 'desc' );
const currentPage = ref( 1 );

// Debounce search
let searchTimer: ReturnType<typeof setTimeout> | null = null;

watch( search, ( value ) => {
	if ( searchTimer ) {
		clearTimeout( searchTimer );
	}

	searchTimer = setTimeout( () => {
		debouncedSearch.value = value;
	}, 300 );
} );

onUnmounted( () => {
	if ( searchTimer ) {
		clearTimeout( searchTimer );
	}
} );

// Action states
const deletingId = ref<number | null>( null );
const duplicatingId = ref<number | null>( null );
const togglingId = ref<number | null>( null );

// Computed
const formsList = computed( () => forms.value?.data ?? [] );

const statusOptions = [
	{ id: 'all', name: 'All Status' },
	{ id: 'active', name: 'Active' },
	{ id: 'inactive', name: 'Inactive' },
];

// Fetch forms
async function fetchForms(): Promise<void> {
	isLoading.value = true;
	error.value = null;

	try {
		const params: Record<string, string> = {
			page: String( currentPage.value ),
			sort_by: sortBy.value,
			sort_direction: sortDirection.value,
		};

		if ( debouncedSearch.value ) {
			params.search = debouncedSearch.value;
		}

		if ( statusFilter.value !== 'all' ) {
			params.status = statusFilter.value;
		}

		const data = await get<PaginatedResponse<Form>>( '/', params );
		forms.value = data;
	} catch ( err ) {
		const message = err instanceof Error ? err.message : 'Failed to load forms.';
		error.value = message;
	} finally {
		isLoading.value = false;
	}
}

// Watchers that trigger re-fetch
watch(
	[debouncedSearch, statusFilter, sortBy, sortDirection, currentPage],
	() => {
		fetchForms();
	},
	{ immediate: true },
);

// Sort handler
function handleSort( column: SortColumn ): void {
	if ( sortBy.value === column ) {
		sortDirection.value = sortDirection.value === 'asc' ? 'desc' : 'asc';
	} else {
		sortBy.value = column;
		sortDirection.value = 'asc';
	}
}

function sortIndicator( column: SortColumn ): string {
	if ( sortBy.value !== column ) {
		return '';
	}

	return sortDirection.value === 'asc' ? ' \u2191' : ' \u2193';
}

function getAriaSortValue( column: SortColumn ): 'ascending' | 'descending' | 'none' {
	if ( sortBy.value !== column ) {
		return 'none';
	}

	return sortDirection.value === 'asc' ? 'ascending' : 'descending';
}

// Action handlers
async function handleDelete( form: Form ): Promise<void> {
	if ( !window.confirm( `Are you sure you want to delete "${form.name}"?` ) ) {
		return;
	}

	deletingId.value = form.id;

	try {
		await del( `/${form.slug}` );
		await fetchForms();
	} catch ( err ) {
		const message = err instanceof Error ? err.message : 'Failed to delete form.';
		error.value = message;
	} finally {
		deletingId.value = null;
	}
}

// TODO: Backend duplicate endpoint would copy fields/steps/notifications.
// Currently only copies form-level settings. A full duplicate API endpoint
// should be added to the package for complete form cloning.
async function handleDuplicate( form: Form ): Promise<void> {
	duplicatingId.value = form.id;

	try {
		const duplicateData: StoreFormRequest = {
			name: `${form.name} (Copy)`,
			description: form.description,
			submit_button_text: form.submit_button_text,
			success_message: form.success_message,
			redirect_url: form.redirect_url,
			is_active: false,
			is_multi_step: form.is_multi_step,
			show_progress_bar: form.show_progress_bar,
			allow_step_navigation: form.allow_step_navigation,
		};

		await post<{ data: Form }>( '/', duplicateData );
		await fetchForms();
	} catch ( err ) {
		const message = err instanceof Error ? err.message : 'Failed to duplicate form.';
		error.value = message;
	} finally {
		duplicatingId.value = null;
	}
}

async function handleTogglePublish( form: Form ): Promise<void> {
	togglingId.value = form.id;

	try {
		await put( `/${form.slug}`, { is_active: !form.is_active } );
		await fetchForms();
	} catch ( err ) {
		const message = err instanceof Error ? err.message : 'Failed to update form status.';
		error.value = message;
	} finally {
		togglingId.value = null;
	}
}

function onSearchInput( e: Event ): void {
	search.value = ( e.target as HTMLInputElement ).value;
	currentPage.value = 1;
}

function onStatusChange( e: Event ): void {
	statusFilter.value = ( e.target as HTMLSelectElement ).value as FormStatusFilter;
	currentPage.value = 1;
}

function formatDate( dateString: string ): string {
	return new Intl.DateTimeFormat( 'en-US', {
		year: 'numeric',
		month: 'short',
		day: 'numeric',
	} ).format( new Date( dateString ) );
}

function isRowProcessing( form: Form ): boolean {
	return duplicatingId.value === form.id
		|| togglingId.value === form.id
		|| deletingId.value === form.id;
}
</script>

<template>
	<div :class="['space-y-6', className]">
		<!-- Header -->
		<div class="flex items-center justify-between">
			<h1 class="text-2xl font-bold">Forms</h1>
			<Button
				color="primary"
				@click="emit( 'create-form' )"
			>
				Create Form
			</Button>
		</div>

		<!-- Filters -->
		<div class="flex flex-wrap items-center gap-3">
			<Input
				type="search"
				class="w-full max-w-xs"
				placeholder="Search forms..."
				:value="search"
				@input="onSearchInput"
			/>

			<Select
				:value="statusFilter"
				:options="statusOptions"
				option-value="id"
				option-label="name"
				@change="onStatusChange"
			/>
		</div>

		<!-- Error -->
		<Alert
			v-if="error"
			color="error"
			dismissible
			@dismiss="error = null"
		>
			{{ error }}
		</Alert>

		<!-- Loading -->
		<div
			v-if="isLoading"
			class="flex items-center justify-center gap-3 py-12"
			role="status"
		>
			<Loading size="md" />
			<span>Loading forms...</span>
		</div>

		<!-- Table -->
		<div
			v-if="!isLoading && formsList.length > 0"
			class="overflow-x-auto"
		>
			<table class="table table-zebra">
				<thead>
					<tr>
						<th :aria-sort="getAriaSortValue( 'name' )">
							<Button
								color="ghost"
								size="sm"
								@click="handleSort( 'name' )"
							>
								Name{{ sortIndicator( 'name' ) }}
							</Button>
						</th>
						<th>Status</th>
						<th>Submissions</th>
						<th :aria-sort="getAriaSortValue( 'created_at' )">
							<Button
								color="ghost"
								size="sm"
								@click="handleSort( 'created_at' )"
							>
								Created{{ sortIndicator( 'created_at' ) }}
							</Button>
						</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					<tr
						v-for="form in formsList"
						:key="form.id"
					>
						<td>
							<div class="flex flex-col">
								<button
									type="button"
									class="link link-hover font-medium text-left"
									@click="emit( 'edit-form', form )"
								>
									{{ form.name }}
								</button>
								<span
									v-if="form.description"
									class="text-sm text-base-content/60"
								>
									{{ form.description }}
								</span>
							</div>
						</td>
						<td>
							<Badge
								:color="form.is_active ? 'success' : 'warning'"
								:value="form.is_active ? 'Active' : 'Inactive'"
							/>
						</td>
						<td>
							<Button
								v-if="showSubmissions"
								color="ghost"
								size="sm"
								@click="emit( 'view-submissions', form )"
							>
								{{ form.total_submissions_count ?? 0 }}
								<Badge
									v-if="( form.unread_submissions_count ?? 0 ) > 0"
									color="info"
									size="sm"
									class="ml-1"
									:value="`${form.unread_submissions_count} new`"
								/>
							</Button>
							<span v-else>
								{{ form.total_submissions_count ?? 0 }}
								<Badge
									v-if="( form.unread_submissions_count ?? 0 ) > 0"
									color="info"
									size="sm"
									class="ml-1"
									:value="`${form.unread_submissions_count} new`"
								/>
							</span>
						</td>
						<td>
							{{ formatDate( form.created_at ) }}
						</td>
						<td>
							<div class="flex items-center gap-1">
								<Button
									color="ghost"
									size="sm"
									title="Edit"
									:disabled="isRowProcessing( form )"
									@click="emit( 'edit-form', form )"
								>
									Edit
								</Button>
								<Button
									color="ghost"
									size="sm"
									title="Duplicate"
									:disabled="isRowProcessing( form )"
									@click="handleDuplicate( form )"
								>
									{{ duplicatingId === form.id ? 'Duplicating...' : 'Duplicate' }}
								</Button>
								<Button
									color="outline"
									size="sm"
									:title="form.is_active ? 'Unpublish' : 'Publish'"
									:disabled="isRowProcessing( form )"
									@click="handleTogglePublish( form )"
								>
									{{
										togglingId === form.id
											? 'Updating...'
											: form.is_active
												? 'Unpublish'
												: 'Publish'
									}}
								</Button>
								<Button
									color="error"
									size="sm"
									title="Delete"
									:disabled="isRowProcessing( form )"
									@click="handleDelete( form )"
								>
									{{ deletingId === form.id ? 'Deleting...' : 'Delete' }}
								</Button>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
		</div>

		<!-- Empty state -->
		<div
			v-if="!isLoading && formsList.length === 0 && !error"
			class="flex flex-col items-center justify-center gap-4 py-16 text-base-content/60"
		>
			<p class="text-lg">No forms found.</p>
			<Button
				color="primary"
				@click="emit( 'create-form' )"
			>
				Create your first form
			</Button>
		</div>

		<!-- Pagination -->
		<Pagination
			v-if="forms && forms.meta.last_page > 1"
			:current-page="forms.meta.current_page"
			:total-pages="forms.meta.last_page"
			@change="currentPage = $event"
		/>
	</div>
</template>
