// resources/js/react/components/fields/TextField.tsx
/**
 * Text-based field components.
 *
 * Renders text, email, phone, number, url, textarea, hidden, password,
 * and time input fields using @artisanpack-ui/react components.
 *
 * @package    ArtisanPack_UI
 * @subpackage Forms
 *
 * @since      1.1.0
 */

import { Input, Textarea } from '@artisanpack-ui/react/form';

import type { FieldComponentProps } from './types';

/**
 * Renders a single-line text input field.
 */
export function TextField( { field, value, error, onChange, displayConfig }: FieldComponentProps ) {
	return (
		<Input
			label={displayConfig.label_position !== 'hidden' ? ( field.label ?? undefined ) : undefined}
			aria-label={displayConfig.label_position === 'hidden' ? ( field.label ?? undefined ) : undefined}
			name={field.name}
			type="text"
			value={String( value ?? '' )}
			placeholder={field.placeholder ?? undefined}
			hint={field.help_text ?? undefined}
			error={error}
			required={field.is_required}
			className={field.css_classes ?? undefined}
			onChange={( e ) => onChange( e.target.value )}
			minLength={field.validation_rules?.min}
			maxLength={field.validation_rules?.max}
			pattern={field.validation_rules?.pattern ?? undefined}
			inline={displayConfig.label_position === 'beside'}
		/>
	);
}

/**
 * Renders an email input field.
 */
export function EmailField( { field, value, error, onChange, displayConfig }: FieldComponentProps ) {
	return (
		<Input
			label={displayConfig.label_position !== 'hidden' ? ( field.label ?? undefined ) : undefined}
			aria-label={displayConfig.label_position === 'hidden' ? ( field.label ?? undefined ) : undefined}
			name={field.name}
			type="email"
			value={String( value ?? '' )}
			placeholder={field.placeholder ?? undefined}
			hint={field.help_text ?? undefined}
			error={error}
			required={field.is_required}
			className={field.css_classes ?? undefined}
			onChange={( e ) => onChange( e.target.value )}
			inline={displayConfig.label_position === 'beside'}
		/>
	);
}

/**
 * Renders a phone input field.
 */
export function PhoneField( { field, value, error, onChange, displayConfig }: FieldComponentProps ) {
	return (
		<Input
			label={displayConfig.label_position !== 'hidden' ? ( field.label ?? undefined ) : undefined}
			aria-label={displayConfig.label_position === 'hidden' ? ( field.label ?? undefined ) : undefined}
			name={field.name}
			type="tel"
			value={String( value ?? '' )}
			placeholder={field.placeholder ?? undefined}
			hint={field.help_text ?? undefined}
			error={error}
			required={field.is_required}
			className={field.css_classes ?? undefined}
			onChange={( e ) => onChange( e.target.value )}
			pattern={field.validation_rules?.pattern ?? undefined}
			inline={displayConfig.label_position === 'beside'}
		/>
	);
}

/**
 * Renders a number input field.
 */
export function NumberField( { field, value, error, onChange, displayConfig }: FieldComponentProps ) {
	return (
		<Input
			label={displayConfig.label_position !== 'hidden' ? ( field.label ?? undefined ) : undefined}
			aria-label={displayConfig.label_position === 'hidden' ? ( field.label ?? undefined ) : undefined}
			name={field.name}
			type="number"
			value={String( value ?? '' )}
			placeholder={field.placeholder ?? undefined}
			hint={field.help_text ?? undefined}
			error={error}
			required={field.is_required}
			className={field.css_classes ?? undefined}
			onChange={( e ) => onChange( e.target.value )}
			min={field.validation_rules?.min}
			max={field.validation_rules?.max}
			step={field.validation_rules?.step}
			inline={displayConfig.label_position === 'beside'}
		/>
	);
}

/**
 * Renders a URL input field.
 */
export function UrlField( { field, value, error, onChange, displayConfig }: FieldComponentProps ) {
	return (
		<Input
			label={displayConfig.label_position !== 'hidden' ? ( field.label ?? undefined ) : undefined}
			aria-label={displayConfig.label_position === 'hidden' ? ( field.label ?? undefined ) : undefined}
			name={field.name}
			type="url"
			value={String( value ?? '' )}
			placeholder={field.placeholder ?? 'https://'}
			hint={field.help_text ?? undefined}
			error={error}
			required={field.is_required}
			className={field.css_classes ?? undefined}
			onChange={( e ) => onChange( e.target.value )}
			inline={displayConfig.label_position === 'beside'}
		/>
	);
}

/**
 * Renders a multi-line textarea field.
 */
export function TextareaField( { field, value, error, onChange, displayConfig }: FieldComponentProps ) {
	return (
		<Textarea
			label={displayConfig.label_position !== 'hidden' ? ( field.label ?? undefined ) : undefined}
			aria-label={displayConfig.label_position === 'hidden' ? ( field.label ?? undefined ) : undefined}
			name={field.name}
			value={String( value ?? '' )}
			placeholder={field.placeholder ?? undefined}
			hint={field.help_text ?? undefined}
			error={error}
			required={field.is_required}
			className={field.css_classes ?? undefined}
			onChange={( e ) => onChange( e.target.value )}
			minLength={field.validation_rules?.min}
			maxLength={field.validation_rules?.max}
		/>
	);
}

/**
 * Renders a hidden input field.
 */
export function HiddenField( { field, value }: FieldComponentProps ) {
	return (
		<input
			type="hidden"
			name={field.name}
			value={String( value ?? '' )}
			readOnly
		/>
	);
}

/**
 * Renders a time input field.
 */
export function TimeField( { field, value, error, onChange, displayConfig }: FieldComponentProps ) {
	return (
		<Input
			label={displayConfig.label_position !== 'hidden' ? ( field.label ?? undefined ) : undefined}
			aria-label={displayConfig.label_position === 'hidden' ? ( field.label ?? undefined ) : undefined}
			name={field.name}
			type="time"
			value={String( value ?? '' )}
			hint={field.help_text ?? undefined}
			error={error}
			required={field.is_required}
			className={field.css_classes ?? undefined}
			onChange={( e ) => onChange( e.target.value )}
			min={field.validation_rules?.min_time ?? undefined}
			max={field.validation_rules?.max_time ?? undefined}
			inline={displayConfig.label_position === 'beside'}
		/>
	);
}

// resources/js/vue/components/fields/TextField.vue
<!--
  Text-based field components wrapper.

  Renders text, email, phone, number, url, textarea, hidden,
  and time input fields using @artisanpack-ui/vue components.

  @package    ArtisanPack_UI
  @subpackage Forms
  @since      1.1.0
-->
<script setup lang="ts">
import { computed } from 'vue';
import { Input, Textarea } from '@artisanpack-ui/vue/form';
import type { FormField, DisplayConfig } from '../../../types/artisanpack-forms';

const props = defineProps<{
	field: FormField;
	modelValue: unknown;
	error?: string;
	displayConfig: DisplayConfig;
}>();

const emit = defineEmits<{
	'update:modelValue': [value: unknown];
}>();

const stringValue = computed( () => String( props.modelValue ?? '' ) );

const showLabel = computed( () => props.displayConfig.label_position !== 'hidden' );
const isInline = computed( () => props.displayConfig.label_position === 'beside' );
const labelText = computed( () => props.field.label ?? undefined );
const ariaLabel = computed( () =>
	props.displayConfig.label_position === 'hidden'
		? ( props.field.label ?? props.field.name )
		: undefined,
);
</script>

<template>
	<!-- Text -->
	<Input
		v-if="field.type === 'text'"
		:label="showLabel ? labelText : undefined"
		:aria-label="ariaLabel"
		:name="field.name"
		type="text"
		:model-value="stringValue"
		:placeholder="field.placeholder ?? undefined"
		:hint="field.help_text ?? undefined"
		:error="error"
		:required="field.is_required"
		:class="field.css_classes ?? undefined"
		:minlength="field.validation_rules?.min"
		:maxlength="field.validation_rules?.max"
		:pattern="field.validation_rules?.pattern ?? undefined"
		:inline="isInline"
		@update:model-value="emit( 'update:modelValue', $event )"
	/>

	<!-- Email -->
	<Input
		v-else-if="field.type === 'email'"
		:label="showLabel ? labelText : undefined"
		:aria-label="ariaLabel"
		:name="field.name"
		type="email"
		:model-value="stringValue"
		:placeholder="field.placeholder ?? undefined"
		:hint="field.help_text ?? undefined"
		:error="error"
		:required="field.is_required"
		:class="field.css_classes ?? undefined"
		:inline="isInline"
		@update:model-value="emit( 'update:modelValue', $event )"
	/>

	<!-- Phone -->
	<Input
		v-else-if="field.type === 'phone'"
		:label="showLabel ? labelText : undefined"
		:aria-label="ariaLabel"
		:name="field.name"
		type="tel"
		:model-value="stringValue"
		:placeholder="field.placeholder ?? undefined"
		:hint="field.help_text ?? undefined"
		:error="error"
		:required="field.is_required"
		:class="field.css_classes ?? undefined"
		:pattern="field.validation_rules?.pattern ?? undefined"
		:inline="isInline"
		@update:model-value="emit( 'update:modelValue', $event )"
	/>

	<!-- Number -->
	<Input
		v-else-if="field.type === 'number'"
		:label="showLabel ? labelText : undefined"
		:aria-label="ariaLabel"
		:name="field.name"
		type="number"
		:model-value="stringValue"
		:placeholder="field.placeholder ?? undefined"
		:hint="field.help_text ?? undefined"
		:error="error"
		:required="field.is_required"
		:class="field.css_classes ?? undefined"
		:min="field.validation_rules?.min"
		:max="field.validation_rules?.max"
		:step="field.validation_rules?.step"
		:inline="isInline"
		@update:model-value="emit( 'update:modelValue', $event )"
	/>

	<!-- URL -->
	<Input
		v-else-if="field.type === 'url'"
		:label="showLabel ? labelText : undefined"
		:aria-label="ariaLabel"
		:name="field.name"
		type="url"
		:model-value="stringValue"
		:placeholder="field.placeholder ?? 'https://'"
		:hint="field.help_text ?? undefined"
		:error="error"
		:required="field.is_required"
		:class="field.css_classes ?? undefined"
		:inline="isInline"
		@update:model-value="emit( 'update:modelValue', $event )"
	/>

	<!-- Textarea -->
	<Textarea
		v-else-if="field.type === 'textarea'"
		:label="showLabel ? labelText : undefined"
		:aria-label="ariaLabel"
		:name="field.name"
		:model-value="stringValue"
		:placeholder="field.placeholder ?? undefined"
		:hint="field.help_text ?? undefined"
		:error="error"
		:required="field.is_required"
		:class="field.css_classes ?? undefined"
		:minlength="field.validation_rules?.min"
		:maxlength="field.validation_rules?.max"
		:inline="isInline"
		@update:model-value="emit( 'update:modelValue', $event )"
	/>

	<!-- Hidden -->
	<input
		v-else-if="field.type === 'hidden'"
		type="hidden"
		:name="field.name"
		:value="stringValue"
		readonly
	/>

	<!-- Time -->
	<Input
		v-else-if="field.type === 'time'"
		:label="showLabel ? labelText : undefined"
		:aria-label="ariaLabel"
		:name="field.name"
		type="time"
		:model-value="stringValue"
		:hint="field.help_text ?? undefined"
		:error="error"
		:required="field.is_required"
		:class="field.css_classes ?? undefined"
		:min="field.validation_rules?.min_time ?? undefined"
		:max="field.validation_rules?.max_time ?? undefined"
		:inline="isInline"
		@update:model-value="emit( 'update:modelValue', $event )"
	/>
</template>
