// resources/js/vue/components/admin/FieldEditor.vue
<!--
  FieldEditor component for per-field settings.

  Adapts its UI based on the selected field type, showing relevant
  configuration options like validation rules, options editor for
  choice fields, file upload settings, and conditional logic.

  @package    ArtisanPack_UI
  @subpackage Forms

  @since      1.1.0
-->
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue';

import { Button, Checkbox, Input, Select, Tabs, Textarea } from '@artisanpack-ui/vue';

import type {
	FieldOption,
	FieldType,
	FieldWidth,
	FormField,
	UpdateFieldRequest,
	ValidationRules,
} from '../../../types/artisanpack-forms';

import ConditionalLogicEditor from './ConditionalLogicEditor.vue';

/** Safely parse a numeric input value, returning undefined for empty or NaN. */
function parseNumericInput( value: string ): number | undefined {
	if ( !value ) {
		return undefined;
	}

	const num = Number( value );

	return Number.isNaN( num ) ? undefined : num;
}

/** Field types that support an options list. */
const OPTION_FIELD_TYPES = new Set<FieldType>( [
	'select',
	'radio',
	'checkbox_group',
	'select_multiple',
] );

/** Field types that don't collect user data. */
const LAYOUT_FIELD_TYPES = new Set<FieldType>( [
	'heading',
	'paragraph',
	'divider',
	'html',
] );

/** Available width options. */
const WIDTH_OPTIONS: Array<{ value: FieldWidth; label: string }> = [
	{ value: 'full', label: 'Full Width' },
	{ value: 'half', label: 'Half (1/2)' },
	{ value: 'third', label: 'Third (1/3)' },
	{ value: 'two-thirds', label: 'Two-Thirds (2/3)' },
];

const props = defineProps<{
	/** The field being edited. */
	field: FormField;
	/** All fields in the form (for conditional logic field references). */
	allFields: FormField[];
	/** Optional CSS class name. */
	class?: string;
}>();

const emit = defineEmits<{
	change: [fieldId: number, data: UpdateFieldRequest];
	delete: [fieldId: number];
	duplicate: [fieldId: number];
	close: [];
}>();

const activeTab = ref<string>( 'general' );

const isLayoutField = computed( () => LAYOUT_FIELD_TYPES.has( props.field.type ) );
const hasOptions    = computed( () => OPTION_FIELD_TYPES.has( props.field.type ) );

// ---------------------------------------------------------------------------
// Debounced field updates (500ms) -- accumulate changes and flush on timer
// or unmount.
// ---------------------------------------------------------------------------

let updateTimer: ReturnType<typeof setTimeout> | null = null;
let pendingUpdates: UpdateFieldRequest               = {};

function flushPendingUpdates(): void {
	if ( updateTimer ) {
		clearTimeout( updateTimer );
		updateTimer = null;
	}

	if ( Object.keys( pendingUpdates ).length > 0 ) {
		emit( 'change', props.field.id, pendingUpdates );
		pendingUpdates = {};
	}
}

function updateField( data: UpdateFieldRequest ): void {
	pendingUpdates = { ...pendingUpdates, ...data };

	if ( updateTimer ) {
		clearTimeout( updateTimer );
	}

	updateTimer = setTimeout( () => {
		emit( 'change', props.field.id, pendingUpdates );
		pendingUpdates = {};
		updateTimer    = null;
	}, 500 );
}

// Flush pending updates when the field changes
watch( () => props.field.id, () => {
	flushPendingUpdates();
} );

onUnmounted( () => {
	flushPendingUpdates();
} );

// ---------------------------------------------------------------------------
// Options editor for choice fields
// ---------------------------------------------------------------------------

const options = computed( (): FieldOption[] => {
	if ( !hasOptions.value ) {
		return [];
	}

	return ( props.field.field_config as { options?: FieldOption[] } )?.options
		?? props.field.options
		?? [];
} );

function handleAddOption(): void {
	const newOptions = [
		...options.value,
		{ label: `Option ${options.value.length + 1}`, value: `option_${options.value.length + 1}` },
	];
	updateField( { field_config: { options: newOptions } } );
}

function handleUpdateOption( index: number, key: 'label' | 'value', value: string ): void {
	const newOptions = options.value.map( ( opt, i ) =>
		i === index ? { ...opt, [key]: value } : opt,
	);
	updateField( { field_config: { options: newOptions } } );
}

function handleRemoveOption( index: number ): void {
	const newOptions = options.value.filter( ( _, i ) => i !== index );
	updateField( { field_config: { options: newOptions } } );
}

// ---------------------------------------------------------------------------
// Validation rules
// ---------------------------------------------------------------------------

const validationRules = computed(
	(): ValidationRules => props.field.validation_rules ?? {},
);

function updateValidation( rules: Partial<ValidationRules> ): void {
	updateField( { validation_rules: { ...validationRules.value, ...rules } } );
}

// ---------------------------------------------------------------------------
// Tabs
// ---------------------------------------------------------------------------

const tabs = computed( () => {
	const items = [
		{ name: 'general', label: 'General' },
	];

	if ( !isLayoutField.value ) {
		items.push( { name: 'validation', label: 'Validation' } );
		items.push( { name: 'conditional', label: 'Conditional' } );
	}

	return items;
} );

// ---------------------------------------------------------------------------
// Helpers for text field type checks used in validation tab
// ---------------------------------------------------------------------------

const isTextField = computed( () => {
	const textTypes: FieldType[] = ['text', 'email', 'url', 'textarea', 'phone'];

	return textTypes.includes( props.field.type );
} );

const isPatternField = computed( () => {
	const patternTypes: FieldType[] = ['text', 'phone'];

	return patternTypes.includes( props.field.type );
} );
</script>

<template>
	<div :class="['flex flex-col gap-0', props.class]">
		<!-- Header -->
		<div class="flex items-center justify-between p-3 border-b border-base-300">
			<h3 class="text-sm font-semibold">
				Edit {{ field.type.replace( '_', ' ' ) }} Field
			</h3>
			<Button
				color="ghost"
				size="sm"
				class="btn-circle"
				aria-label="Close field editor"
				@click="emit( 'close' )"
			>
				&times;
			</Button>
		</div>

		<!-- Tabs -->
		<Tabs
			variant="bordered"
			:tabs="tabs"
			:active-tab="activeTab"
			@change="activeTab = $event"
		>
			<!-- General Tab -->
			<template #general>
				<div class="space-y-4 p-4">
					<!-- Label -->
					<Input
						label="Label"
						:model-value="field.label ?? ''"
						@update:model-value="updateField( { label: ($event as string) } )"
					/>

					<!-- Name (machine name) -->
					<Input
						label="Name"
						:model-value="field.name"
						hint="Machine-readable name. Used as the form data key."
						@update:model-value="updateField( { name: ($event as string) } )"
					/>

					<!-- Placeholder (non-layout only) -->
					<Input
						v-if="!isLayoutField && field.type !== 'checkbox' && field.type !== 'radio'"
						label="Placeholder"
						:model-value="field.placeholder ?? ''"
						@update:model-value="updateField( { placeholder: ($event as string) || null } )"
					/>

					<!-- Help text -->
					<Input
						v-if="!isLayoutField"
						label="Help Text"
						:model-value="field.help_text ?? ''"
						@update:model-value="updateField( { help_text: ($event as string) || null } )"
					/>

					<!-- Default value -->
					<Input
						v-if="!isLayoutField && field.type !== 'file'"
						label="Default Value"
						:model-value="field.default_value ?? ''"
						@update:model-value="updateField( { default_value: ($event as string) || null } )"
					/>

					<!-- Required toggle -->
					<Checkbox
						v-if="!isLayoutField"
						label="Required"
						:model-value="field.is_required"
						@update:model-value="updateField( { is_required: ($event as boolean) } )"
					/>

					<!-- Width -->
					<Select
						label="Width"
						:model-value="field.width"
						:options="WIDTH_OPTIONS"
						option-value="value"
						option-label="label"
						@update:model-value="updateField( { width: ($event as FieldWidth) } )"
					/>

					<!-- CSS Classes -->
					<Input
						label="CSS Classes"
						:model-value="field.css_classes ?? ''"
						@update:model-value="updateField( { css_classes: ($event as string) || null } )"
					/>

					<!-- HTML Content (for html field type) -->
					<Textarea
						v-if="field.type === 'html'"
						label="HTML Content"
						:rows="6"
						:model-value="field.default_value ?? ''"
						@update:model-value="updateField( { default_value: ($event as string) } )"
					/>

					<!-- Heading/Paragraph content -->
					<template v-if="field.type === 'heading' || field.type === 'paragraph'">
						<Input
							v-if="field.type === 'heading'"
							label="Content"
							:model-value="field.default_value ?? ''"
							@update:model-value="updateField( { default_value: ($event as string) } )"
						/>
						<Textarea
							v-else
							label="Content"
							:rows="4"
							:model-value="field.default_value ?? ''"
							@update:model-value="updateField( { default_value: ($event as string) } )"
						/>
					</template>

					<!-- Options editor for choice fields -->
					<div v-if="hasOptions" class="space-y-2">
						<label class="label">
							<span class="label-text font-medium">Options</span>
						</label>
						<div
							v-for="( option, index ) in options"
							:key="index"
							class="flex items-center gap-2"
						>
							<Input
								placeholder="Label"
								:model-value="option.label"
								class="flex-1"
								@update:model-value="handleUpdateOption( index, 'label', ($event as string) )"
							/>
							<Input
								placeholder="Value"
								:model-value="option.value"
								class="flex-1"
								@update:model-value="handleUpdateOption( index, 'value', ($event as string) )"
							/>
							<Button
								color="ghost"
								size="sm"
								class="btn-circle"
								title="Remove option"
								@click="handleRemoveOption( index )"
							>
								&times;
							</Button>
						</div>
						<Button
							color="ghost"
							size="sm"
							@click="handleAddOption"
						>
							Add Option
						</Button>
					</div>

					<!-- File field config -->
					<div v-if="field.type === 'file'" class="space-y-4">
						<Input
							label="Max File Size (KB)"
							type="number"
							:min="0"
							:model-value="String( validationRules.max_size ?? '' )"
							@update:model-value="updateValidation( { max_size: parseNumericInput( ($event as string) ) } )"
						/>
						<Input
							label="Allowed File Types (comma-separated MIME types)"
							:model-value="validationRules.allowed_types?.join( ', ' ) ?? ''"
							@update:model-value="updateValidation( {
								allowed_types: ($event as string)
									? ($event as string).split( ',' ).map( ( s: string ) => s.trim() )
									: undefined,
							} )"
						/>
					</div>
				</div>
			</template>

			<!-- Validation Tab -->
			<template #validation>
				<div class="space-y-4 p-4">
					<!-- Min/Max for text fields -->
					<template v-if="isTextField">
						<Input
							label="Min Length"
							type="number"
							:min="0"
							:model-value="String( validationRules.min ?? '' )"
							@update:model-value="updateValidation( { min: parseNumericInput( ($event as string) ) } )"
						/>
						<Input
							label="Max Length"
							type="number"
							:min="0"
							:model-value="String( validationRules.max ?? '' )"
							@update:model-value="updateValidation( { max: parseNumericInput( ($event as string) ) } )"
						/>
					</template>

					<!-- Min/Max/Step for number -->
					<template v-if="field.type === 'number'">
						<Input
							label="Minimum"
							type="number"
							:model-value="String( validationRules.min ?? '' )"
							@update:model-value="updateValidation( { min: parseNumericInput( ($event as string) ) } )"
						/>
						<Input
							label="Maximum"
							type="number"
							:model-value="String( validationRules.max ?? '' )"
							@update:model-value="updateValidation( { max: parseNumericInput( ($event as string) ) } )"
						/>
						<Input
							label="Step"
							type="number"
							:min="0"
							:model-value="String( validationRules.step ?? '' )"
							@update:model-value="updateValidation( { step: parseNumericInput( ($event as string) ) } )"
						/>
					</template>

					<!-- Date range -->
					<template v-if="field.type === 'date'">
						<Input
							label="Min Date"
							type="date"
							:model-value="validationRules.min_date ?? ''"
							@update:model-value="updateValidation( { min_date: ($event as string) || undefined } )"
						/>
						<Input
							label="Max Date"
							type="date"
							:model-value="validationRules.max_date ?? ''"
							@update:model-value="updateValidation( { max_date: ($event as string) || undefined } )"
						/>
					</template>

					<!-- Time range -->
					<template v-if="field.type === 'time'">
						<Input
							label="Min Time"
							type="time"
							:model-value="validationRules.min_time ?? ''"
							@update:model-value="updateValidation( { min_time: ($event as string) || undefined } )"
						/>
						<Input
							label="Max Time"
							type="time"
							:model-value="validationRules.max_time ?? ''"
							@update:model-value="updateValidation( { max_time: ($event as string) || undefined } )"
						/>
					</template>

					<!-- Pattern -->
					<Input
						v-if="isPatternField"
						label="Pattern (RegExp)"
						:model-value="validationRules.pattern ?? ''"
						placeholder="e.g. ^[A-Z]{2}[0-9]{4}$"
						hint="Regular expression pattern for input validation."
						@update:model-value="updateValidation( { pattern: ($event as string) || undefined } )"
					/>
				</div>
			</template>

			<!-- Conditional Tab -->
			<template #conditional>
				<ConditionalLogicEditor
					:value="field.conditional_logic"
					:fields="allFields"
					:exclude-field-id="field.id"
					@update:value="updateField( { conditional_logic: $event } )"
				/>
			</template>
		</Tabs>

		<!-- Footer actions -->
		<div class="flex gap-2 justify-end p-3 border-t border-base-300">
			<Button
				color="ghost"
				size="sm"
				@click="emit( 'duplicate', field.id )"
			>
				Duplicate
			</Button>
			<Button
				color="error"
				size="sm"
				@click="() => {
					if ( window.confirm( 'Are you sure you want to delete this field?' ) ) {
						emit( 'delete', field.id );
					}
				}"
			>
				Delete
			</Button>
		</div>
	</div>
</template>

// resources/js/react/components/admin/FieldEditor.tsx
/**
 * FieldEditor component for per-field settings.
 *
 * Adapts its UI based on the selected field type, showing relevant
 * configuration options like validation rules, options editor for
 * choice fields, file upload settings, and conditional logic.
 *
 * @package    ArtisanPack_UI
 * @subpackage Forms
 *
 * @since      1.1.0
 */

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { Button, Checkbox, Input, Select, Tabs, Textarea } from '@artisanpack-ui/react';

import type {
	FieldOption,
	FieldType,
	FieldWidth,
	FormField,
	UpdateFieldRequest,
	ValidationRules,
} from '../../../types/artisanpack-forms';

import { ConditionalLogicEditor } from './ConditionalLogicEditor';

/** Safely parse a numeric input value, returning undefined for empty or NaN. */
function parseNumericInput( value: string ): number | undefined {
	if ( !value ) {
		return undefined;
	}

	const num = Number( value );

	return Number.isNaN( num ) ? undefined : num;
}

/** Field types that support an options list. */
const OPTION_FIELD_TYPES: Set<FieldType> = new Set( [
	'select',
	'radio',
	'checkbox_group',
	'select_multiple',
] );

/** Field types that don't collect user data. */
const LAYOUT_FIELD_TYPES: Set<FieldType> = new Set( [
	'heading',
	'paragraph',
	'divider',
	'html',
] );

/** Available width options. */
const WIDTH_OPTIONS: Array<{ value: FieldWidth; label: string }> = [
	{ value: 'full', label: 'Full Width' },
	{ value: 'half', label: 'Half (1/2)' },
	{ value: 'third', label: 'Third (1/3)' },
	{ value: 'two-thirds', label: 'Two-Thirds (2/3)' },
];

/** Props for the FieldEditor component. */
export interface FieldEditorProps {
	/** The field being edited. */
	field: FormField;
	/** All fields in the form (for conditional logic field references). */
	allFields: FormField[];
	/** Callback when a field property changes. */
	onChange: ( fieldId: number, data: UpdateFieldRequest ) => void;
	/** Callback to delete the field. */
	onDelete: ( fieldId: number ) => void;
	/** Callback to duplicate the field. */
	onDuplicate: ( fieldId: number ) => void;
	/** Callback to close the editor panel. */
	onClose: () => void;
	/** Optional CSS class name. */
	className?: string;
}

/**
 * Per-field settings editor panel.
 *
 * @example
 * ```tsx
 * <FieldEditor
 *   field={selectedField}
 *   allFields={form.fields}
 *   onChange={(id, data) => updateField(id, data)}
 *   onDelete={(id) => deleteField(id)}
 *   onDuplicate={(id) => duplicateField(id)}
 *   onClose={() => setSelectedField(null)}
 * />
 * ```
 */
export function FieldEditor( {
	field,
	allFields,
	onChange,
	onDelete,
	onDuplicate,
	onClose,
	className,
}: FieldEditorProps ): React.ReactElement {
	const [activeTab, setActiveTab] = useState<string>( 'general' );

	const isLayoutField = LAYOUT_FIELD_TYPES.has( field.type );
	const hasOptions = OPTION_FIELD_TYPES.has( field.type );

	const updateTimerRef = useRef<ReturnType<typeof setTimeout> | null>( null );
	const pendingUpdatesRef = useRef<UpdateFieldRequest>( {} );

	const updateField = useCallback(
		( data: UpdateFieldRequest ) => {
			pendingUpdatesRef.current = { ...pendingUpdatesRef.current, ...data };

			if ( updateTimerRef.current ) {
				clearTimeout( updateTimerRef.current );
			}

			updateTimerRef.current = setTimeout( () => {
				onChange( field.id, pendingUpdatesRef.current );
				pendingUpdatesRef.current = {};
			}, 500 );
		},
		[field.id, onChange],
	);

	useEffect( () => {
		return () => {
			if ( updateTimerRef.current ) {
				clearTimeout( updateTimerRef.current );

				if ( Object.keys( pendingUpdatesRef.current ).length > 0 ) {
					onChange( field.id, pendingUpdatesRef.current );
					pendingUpdatesRef.current = {};
				}
			}
		};
	}, [field.id, onChange] );

	// Options editor for choice fields
	const options = useMemo( (): FieldOption[] => {
		if ( !hasOptions ) {
			return [];
		}

		return ( field.field_config as { options?: FieldOption[] } )?.options ?? field.options ?? [];
	}, [field, hasOptions] );

	const handleAddOption = useCallback( () => {
		const newOptions = [
			...options,
			{ label: `Option ${options.length + 1}`, value: `option_${options.length + 1}` },
		];
		updateField( { field_config: { options: newOptions } } );
	}, [options, updateField] );

	const handleUpdateOption = useCallback(
		( index: number, key: 'label' | 'value', value: string ) => {
			const newOptions = options.map( ( opt, i ) =>
				i === index ? { ...opt, [key]: value } : opt,
			);
			updateField( { field_config: { options: newOptions } } );
		},
		[options, updateField],
	);

	const handleRemoveOption = useCallback(
		( index: number ) => {
			const newOptions = options.filter( ( _, i ) => i !== index );
			updateField( { field_config: { options: newOptions } } );
		},
		[options, updateField],
	);

	// Validation rules
	const validationRules = useMemo(
		(): ValidationRules => field.validation_rules ?? {},
		[field.validation_rules],
	);

	const updateValidation = useCallback(
		( rules: Partial<ValidationRules> ) => {
			updateField( { validation_rules: { ...validationRules, ...rules } } );
		},
		[validationRules, updateField],
	);

	// Build tabs array — Tabs component uses `name` (not `id`) as the key
	const tabs = useMemo( () => {
		const tabItems = [
			{
				name: 'general',
				label: 'General',
				content: (
					<GeneralTabContent
						field={field}
						isLayoutField={isLayoutField}
						hasOptions={hasOptions}
						options={options}
						validationRules={validationRules}
						updateField={updateField}
						updateValidation={updateValidation}
						handleAddOption={handleAddOption}
						handleUpdateOption={handleUpdateOption}
						handleRemoveOption={handleRemoveOption}
					/>
				),
			},
		];

		if ( !isLayoutField ) {
			tabItems.push( {
				name: 'validation',
				label: 'Validation',
				content: (
					<ValidationTabContent
						field={field}
						validationRules={validationRules}
						updateValidation={updateValidation}
					/>
				),
			} );
			tabItems.push( {
				name: 'conditional',
				label: 'Conditional',
				content: (
					<ConditionalLogicEditor
						value={field.conditional_logic}
						onChange={( logic ) => updateField( { conditional_logic: logic } )}
						fields={allFields}
						excludeFieldId={field.id}
					/>
				),
			} );
		}

		return tabItems;
	}, [
		field, isLayoutField, hasOptions, options, validationRules,
		allFields, updateField, updateValidation,
		handleAddOption, handleUpdateOption, handleRemoveOption,
	] );

	return (
		<div className={`flex flex-col gap-0 ${className ?? ''}`}>
			{/* Header */}
			<div className="flex items-center justify-between p-3 border-b border-base-300">
				<h3 className="text-sm font-semibold">
					Edit {field.type.replace( '_', ' ' )} Field
				</h3>
				<Button
					color="ghost"
					size="sm"
					className="btn-circle"
					onClick={onClose}
					aria-label="Close field editor"
				>
					&times;
				</Button>
			</div>

			{/* Tabs */}
			<Tabs
				variant="bordered"
				tabs={tabs}
				activeTab={activeTab}
				onChange={setActiveTab}
			/>

			{/* Footer actions */}
			<div className="flex gap-2 justify-end p-3 border-t border-base-300">
				<Button
					color="ghost"
					size="sm"
					onClick={() => onDuplicate( field.id )}
				>
					Duplicate
				</Button>
				<Button
					color="error"
					size="sm"
					onClick={() => {
						if ( window.confirm( 'Are you sure you want to delete this field?' ) ) {
							onDelete( field.id );
						}
					}}
				>
					Delete
				</Button>
			</div>
		</div>
	);
}

// ---------------------------------------------------------------------------
// GeneralTabContent (inline sub-component)
// ---------------------------------------------------------------------------

interface GeneralTabContentProps {
	field: FormField;
	isLayoutField: boolean;
	hasOptions: boolean;
	options: FieldOption[];
	validationRules: ValidationRules;
	updateField: ( data: UpdateFieldRequest ) => void;
	updateValidation: ( rules: Partial<ValidationRules> ) => void;
	handleAddOption: () => void;
	handleUpdateOption: ( index: number, key: 'label' | 'value', value: string ) => void;
	handleRemoveOption: ( index: number ) => void;
}

function GeneralTabContent( {
	field,
	isLayoutField,
	hasOptions,
	options,
	validationRules,
	updateField,
	updateValidation,
	handleAddOption,
	handleUpdateOption,
	handleRemoveOption,
}: GeneralTabContentProps ): React.ReactElement {
	return (
		<div className="space-y-4 p-4">
			{/* Label */}
			<Input
				label="Label"
				value={field.label ?? ''}
				onChange={( e ) => updateField( { label: e.target.value } )}
			/>

			{/* Name (machine name) */}
			<Input
				label="Name"
				value={field.name}
				onChange={( e ) => updateField( { name: e.target.value } )}
				hint="Machine-readable name. Used as the form data key."
			/>

			{/* Placeholder (non-layout only) */}
			{!isLayoutField && field.type !== 'checkbox' && field.type !== 'radio' && (
				<Input
					label="Placeholder"
					value={field.placeholder ?? ''}
					onChange={( e ) => updateField( { placeholder: e.target.value || null } )}
				/>
			)}

			{/* Help text */}
			{!isLayoutField && (
				<Input
					label="Help Text"
					value={field.help_text ?? ''}
					onChange={( e ) => updateField( { help_text: e.target.value || null } )}
				/>
			)}

			{/* Default value */}
			{!isLayoutField && field.type !== 'file' && (
				<Input
					label="Default Value"
					value={field.default_value ?? ''}
					onChange={( e ) => updateField( { default_value: e.target.value || null } )}
				/>
			)}

			{/* Required toggle */}
			{!isLayoutField && (
				<Checkbox
					label="Required"
					checked={field.is_required}
					onChange={( e ) => updateField( { is_required: e.target.checked } )}
				/>
			)}

			{/* Width */}
			<Select
				label="Width"
				value={field.width}
				options={WIDTH_OPTIONS}
				optionValue="value"
				optionLabel="label"
				onChange={( e ) => updateField( { width: e.target.value as FieldWidth } )}
			/>

			{/* CSS Classes */}
			<Input
				label="CSS Classes"
				value={field.css_classes ?? ''}
				onChange={( e ) => updateField( { css_classes: e.target.value || null } )}
			/>

			{/* HTML Content (for html field type) */}
			{field.type === 'html' && (
				<Textarea
					label="HTML Content"
					rows={6}
					value={field.default_value ?? ''}
					onChange={( e ) => updateField( { default_value: e.target.value } )}
				/>
			)}

			{/* Heading/Paragraph content */}
			{( field.type === 'heading' || field.type === 'paragraph' ) && (
				<>
					{field.type === 'heading' ? (
						<Input
							label="Content"
							value={field.default_value ?? ''}
							onChange={( e ) => updateField( { default_value: e.target.value } )}
						/>
					) : (
						<Textarea
							label="Content"
							rows={4}
							value={field.default_value ?? ''}
							onChange={( e ) => updateField( { default_value: e.target.value } )}
						/>
					)}
				</>
			)}

			{/* Options editor for choice fields */}
			{hasOptions && (
				<div className="space-y-2">
					<label className="label">
						<span className="label-text font-medium">Options</span>
					</label>
					{options.map( ( option, index ) => (
						<div key={index} className="flex items-center gap-2">
							<Input
								placeholder="Label"
								value={option.label}
								onChange={( e ) => handleUpdateOption( index, 'label', e.target.value )}
								className="flex-1"
							/>
							<Input
								placeholder="Value"
								value={option.value}
								onChange={( e ) => handleUpdateOption( index, 'value', e.target.value )}
								className="flex-1"
							/>
							<Button
								color="ghost"
								size="sm"
								className="btn-circle"
								onClick={() => handleRemoveOption( index )}
								title="Remove option"
							>
								&times;
							</Button>
						</div>
					) )}
					<Button
						color="ghost"
						size="sm"
						onClick={handleAddOption}
					>
						Add Option
					</Button>
				</div>
			)}

			{/* File field config */}
			{field.type === 'file' && (
				<div className="space-y-4">
					<Input
						label="Max File Size (KB)"
						type="number"
						min={0}
						value={validationRules.max_size ?? ''}
						onChange={( e ) => updateValidation( {
							max_size: parseNumericInput( e.target.value ),
						} )}
					/>
					<Input
						label="Allowed File Types (comma-separated MIME types)"
						value={validationRules.allowed_types?.join( ', ' ) ?? ''}
						onChange={( e ) => updateValidation( {
							allowed_types: e.target.value
								? e.target.value.split( ',' ).map( ( s ) => s.trim() )
								: undefined,
						} )}
					/>
				</div>
			)}
		</div>
	);
}

// ---------------------------------------------------------------------------
// ValidationTabContent (inline sub-component)
// ---------------------------------------------------------------------------

interface ValidationTabContentProps {
	field: FormField;
	validationRules: ValidationRules;
	updateValidation: ( rules: Partial<ValidationRules> ) => void;
}

function ValidationTabContent( {
	field,
	validationRules,
	updateValidation,
}: ValidationTabContentProps ): React.ReactElement {
	return (
		<div className="space-y-4 p-4">
			{/* Min/Max for text fields */}
			{( field.type === 'text' || field.type === 'email' || field.type === 'url' ||
				field.type === 'textarea' || field.type === 'phone' ) && (
				<>
					<Input
						label="Min Length"
						type="number"
						min={0}
						value={validationRules.min ?? ''}
						onChange={( e ) => updateValidation( {
							min: parseNumericInput( e.target.value ),
						} )}
					/>
					<Input
						label="Max Length"
						type="number"
						min={0}
						value={validationRules.max ?? ''}
						onChange={( e ) => updateValidation( {
							max: parseNumericInput( e.target.value ),
						} )}
					/>
				</>
			)}

			{/* Min/Max/Step for number */}
			{field.type === 'number' && (
				<>
					<Input
						label="Minimum"
						type="number"
						value={validationRules.min ?? ''}
						onChange={( e ) => updateValidation( {
							min: parseNumericInput( e.target.value ),
						} )}
					/>
					<Input
						label="Maximum"
						type="number"
						value={validationRules.max ?? ''}
						onChange={( e ) => updateValidation( {
							max: parseNumericInput( e.target.value ),
						} )}
					/>
					<Input
						label="Step"
						type="number"
						min={0}
						value={validationRules.step ?? ''}
						onChange={( e ) => updateValidation( {
							step: parseNumericInput( e.target.value ),
						} )}
					/>
				</>
			)}

			{/* Date range */}
			{field.type === 'date' && (
				<>
					<Input
						label="Min Date"
						type="date"
						value={validationRules.min_date ?? ''}
						onChange={( e ) => updateValidation( { min_date: e.target.value || undefined } )}
					/>
					<Input
						label="Max Date"
						type="date"
						value={validationRules.max_date ?? ''}
						onChange={( e ) => updateValidation( { max_date: e.target.value || undefined } )}
					/>
				</>
			)}

			{/* Time range */}
			{field.type === 'time' && (
				<>
					<Input
						label="Min Time"
						type="time"
						value={validationRules.min_time ?? ''}
						onChange={( e ) => updateValidation( { min_time: e.target.value || undefined } )}
					/>
					<Input
						label="Max Time"
						type="time"
						value={validationRules.max_time ?? ''}
						onChange={( e ) => updateValidation( { max_time: e.target.value || undefined } )}
					/>
				</>
			)}

			{/* Pattern */}
			{( field.type === 'text' || field.type === 'phone' ) && (
				<Input
					label="Pattern (RegExp)"
					value={validationRules.pattern ?? ''}
					onChange={( e ) => updateValidation( { pattern: e.target.value || undefined } )}
					placeholder="e.g. ^[A-Z]{2}[0-9]{4}$"
					hint="Regular expression pattern for input validation."
				/>
			)}
		</div>
	);
}
